
DATA: DESIGUALDAD ECONÓMICA o INCLUSIÓN SOCIAL

```{r}
library(rio)
link="https://github.com/marielahorna/Estad-stica-2/raw/master/Inclusive%201.xlsx"
#descargando en carpeta actual
download.file(link, "file.xlsx")
data_inclusive= import_list('file.xlsx',rbind = FALSE,na ="#N/A")


data1=data_inclusive[[1]]
data2=data_inclusive[[2]]
data3=data_inclusive[[3]]
```

```{r}
names(data1)[1]="Country"
names(data2)[1]="Country"
names(data3)[1]="Country"

data1$...3=NULL
data1$...5=NULL
data1$...7=NULL
data1$...9=NULL
data1$...11=NULL
data1$...13=NULL
data1$...15=NULL
data1$...17=NULL
data1$...19=NULL
data1$...21=NULL
  
str(data1)
data1[,]=lapply(data1[,], trimws,whitespace= "[\\h\\v]")
data1[,c(2:13)]=lapply(data1[,c(2:13)], as.numeric)
data2=na.omit(data2)
```


```{r}
data2$...3=NULL
data2$...5=NULL
data2$...7=NULL
data2$...9=NULL
data2$...11=NULL
data2$...13=NULL
data2$...15=NULL
data2$...16=NULL
data2$...18=NULL
data2$...20=NULL
data2$...22=NULL
data2$...24=NULL
  
str(data2)
data2[,]=lapply(data2[,], trimws,whitespace= "[\\h\\v]")
data[,c(2:13)]=lapply(data2[,c(2:13)], as.numeric)
data1=na.omit(data1)
```

```{r}
data3$...3=NULL
data3$...5=NULL
data3$...7=NULL
data3$...9=NULL
data3$...11=NULL
data3$...13=NULL
data3$...15=NULL
data3$...17=NULL
data3$...19=NULL
data3$...20=NULL
data3$...22=NULL
data3$...23=NULL
data3$...25=NULL
  
str(data3)
data3[,]=lapply(data3[,], trimws,whitespace= "[\\h\\v]")
data3[,c(2:13)]=lapply(data3[,c(2:13)], as.numeric)
data3=na.omit(data3)
```

```{r}
thedata1=data1[,c(1,7:8)]
thedata2=data2[,c(1,7:8)]
thedata3=data3[,c(1,7:8)]

nombres=c("Country","Poverty_Rate","Wealth_Gini")
names(thedata1)=nombres
names(thedata2)=nombres
names(thedata3)=nombres

row.names(thedata1)=NULL
row.names(thedata2)=NULL
row.names(thedata3)=NULL

inclusividad=rbind(thedata1,thedata2,thedata3)
row.names(inclusividad)=inclusividad$Country
inclusividad$Country=NULL
```


DATA: NIVEL DE LIBERTADES

```{r}
library(rio)
Link1="https://github.com/MYance19/BASES-PARCIAL-Y-FINAL/raw/master/Country%20and%20Territory%20Ratings%20and%20Statuses%20FIW1973-2018.xlsx"
download.file(Link1,"file.xlsx")
liberties= import_list("file.xlsx",rbind=FALSE)
```

```{r}

CountryStatus=liberties[[2]]
TerritoryRatings=liberties[[3]]
```

```{r}
CountryStatus=CountryStatus[,-c(2:50)]
CountryStatus=CountryStatus[,-c(2:50)]
CountryStatus=CountryStatus[,-c(2:20)]
CountryStatus=CountryStatus[,-c(2:13)]
CountryStatus=CountryStatus[-c(1:2),]
names(CountryStatus)= c('COUNTRY', '2016POLITICAL RIGHTS',"2016CIVIL LIBERTIES","2016FREEDOM STATUS",'2017POLITICAL RIGHTS',"2017CIVIL LIBERTIES","2017 FREEDOM STATUS")
CountryStatus$`2016FREEDOM STATUS`=NULL
CountryStatus$`2017 FREEDOM STATUS`=NULL
CountryStatus[1:7]=lapply(CountryStatus[1:7], trimws,whitespace = "[\\h\\v]")
CountryStatus[,-c(1,4,7)]=lapply(CountryStatus[,-c(1,4,7)], as.numeric)
CountryStatus=na.omit(CountryStatus)
row.names(CountryStatus)=CountryStatus$COUNTRY
CountryStatus=CountryStatus[,-c(1)]
str(CountryStatus)
```

DATA: JUSTICIA CIVIL


```{r}
library(rio)
lk="https://github.com/marielahorna/Estad-stica-2/raw/master/justice.xlsx"
civil_justice=import(lk)
```

```{r}
names(civil_justice)
names(civil_justice)[1]="Country"
names(civil_justice)[2]="Civil_Justice"
names(civil_justice)[3]="Rank"

str(civil_justice)
civil_justice$Rank=NULL
civil_justice=na.omit(civil_justice)
row.names(civil_justice)=civil_justice$Country
civil_justice$Country=NULL
```

DATA: ACCOUNTABILITY

```{r}
library(rio)
link="https://github.com/marielahorna/Estad-stica-2/raw/master/wgidataset.xlsx"
#descargando en carpeta actual
download.file(link, "file.xlsx")
several= import_list('file.xlsx',rbind = FALSE,na ="#N/A")

voice=several[[2]]


names(voice)=paste0(voice[13,],voice[14,])

voice=voice[-c(1:14),]


estCols=grep('Estimate',x =names(voice))
voice=voice[,c(1,2,estCols)]

#Eliminar las columnas que no me sirven
voice=voice[,c(1,20,21)]

voice[,c(1:3)]=lapply(voice[,c(1:3)], trimws,whitespace= "[\\h\\v]")
voice[,c(2:3)]=lapply(voice[,c(2:3)], as.numeric)

names(voice)[1]="Country"


row.names(voice)=voice$Country
voice=na.omit(voice)
```



